sonar.projectKey=patient-service
sonar.projectName=Patient Service
sonar.projectVersion=1.0.0
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target
sonar.sourceEncoding=UTF-8
